services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8888:80"
    volumes:
      - ./backend:/var/www/project:rw
      - ./.docker/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - mysql
  backend:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: backend
    environment:
      PHP_IDE_CONFIG: serverName=backend
    volumes:
      - ./:/var/www/project:rw
      - ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
#    env_file:
#      - ./backend/.env
  mysql:
    image: mysql:8.3
    container_name: mysql
    volumes:
      - ../db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_USER: user
      MYSQL_PASSWORD: qwerty
      MYSQL_DATABASE: laravel
